name: Merge - Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - ob-v*
jobs:
  run_merge-template:
    name: Merge - Build and Deploy
    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/reusable-merge.yml@main
    secrets: inherit
    with:
      componentName: secure-api-gateway-parent
