name: PR - Build and Deploy
on:
  pull_request:
jobs:
  run_pr-template:
    name: PR - Build and Deploy
    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/reusable-pr.yml@1389-standard-steps-for-workflows
    secrets: inherit
    with:
      componentName: secure-api-gateway-parent
