name: release-prepare
run-name: Prepare Release '${{ inputs.release_version_number }}'
on:
  workflow_call:
    inputs:
      release_version_number:
        required: true
        type: string
      java_version:
        required: false
        type: string
        default: '17'
    outputs:
      release_tag_ref:
        description: "Release tag"
        value: ${{ jobs.release_prepare.outputs.release_tag_ref }}
    secrets:
      GPG_PRIVATE_KEY_BOT:
        required: true
      GPG_KEY_PASSPHRASE_BOT:
        required: true
      GIT_COMMIT_USERNAME_BOT:
        required: true
      GIT_COMMIT_AUTHOR_EMAIL_BOT:
        required: true
      release_github_token:
        required: true


jobs:
  release_prepare:
    name: Release prepare
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      release_tag_ref: ${{ steps.create_release_context.outputs.release_tag }}

    steps:
      # https://github.com/actions/checkout
      - name: Checkout Parent Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.release_github_token }}

      # set java and cache
      - name: Set Java and Maven Cache
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ inputs.java_version }}
          architecture: x64
          cache: 'maven'

      # Create tag context variable
      - name: Create Release Context
        id: create_release_context
        run: |
          echo "release_tag=v${{ inputs.release_version_number }}" >> $GITHUB_OUTPUT
          git config --global user.name "fropenbanking"
          git config --global user.email "obst@forgerock.com"

      # Release prepare
      # - Change the version in the POM from x-SNAPSHOT to the new version provided for the release_version_number input
      # - Transform the SCM information in the POM to include the final destination of the tag
      # - Commit the modified POM
      # - Tag the code in the SCM with a version name (v${{ inputs.release_version_number }})
      # See in the pom file the configuration '<tagNameFormat>v@{project.version}</tagNameFormat>'
      # - Bump the version in the POM to a new value, the next development iteration (y-SNAPSHOT)
      # - Commit the modified POM
      - name: release prepare
        run: |
          mvn -B release:clean release:prepare -DreleaseVersion=${{ inputs.release_version_number }} -DpushChanges=false

      # pushing changes done by the release prepare step (development snapshot version)
      - name: push development snapshot version
        run: |
          git push origin ${{ steps.create_release_context.outputs.release_tag }}
          git push -f
