name: release-prepare
run-name: Prepare Release '${{ inputs.release_version_number }}'
on:
  workflow_call:
    inputs:
      release_version_number:
        required: true
        type: string
      java_version:
        required: false
        type: string
        default: '14'
    outputs:
      release_branch_ref:
        description: "Release branch"
        value: ${{ jobs.release_prepare.outputs.release_branch_ref }}
      release_tag_ref:
        description: "Release tag"
        value: ${{ jobs.release_prepare.outputs.release_tag_ref }}
    secrets:
      GIT_COMMIT_USERNAME_BOT:
        required: true
      GIT_COMMIT_AUTHOR_EMAIL_BOT:
        required: true
env:
  # Set the environment with secrets provided by the caller (secrets section)
  GIT_AUTHOR_NAME: ${{ secrets.GIT_COMMIT_USERNAME_BOT }}
  GIT_AUTHOR_EMAIL: ${{ secrets.GIT_COMMIT_AUTHOR_EMAIL_BOT }}
  GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMIT_USERNAME_BOT }}
  GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMIT_AUTHOR_EMAIL_BOT }}

jobs:
  release_prepare:
    name: Release prepare
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      release_branch_ref: ${{ steps.create_release_context.outputs.release_branch }}
      release_tag_ref: ${{ steps.create_release_context.outputs.release_tag }}

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
        id: checkout_master
        name: checkout master

      # Create branch context variable
      - name: Create release context
        id: create_release_context
        run: |
          echo "release_branch=release/${{ inputs.release_version_number }}" >> $GITHUB_OUTPUT
          echo "release_tag=v${{ inputs.release_version_number }}" >> $GITHUB_OUTPUT

      # create the release branch with release version number provided
      - name: create release branch
        id: create_release_branch
        run: |
          echo "Release branch: ${{ steps.create_release_context.outputs.release_branch }}"
          git checkout -b ${{ steps.create_release_context.outputs.release_branch }}

      # push the branch to remote repository
      - name: push branch
        id: push_branch
        run: |
          git push -f --set-upstream origin ${{ steps.create_release_context.outputs.release_branch }}
          