name: release-publish
run-name: GitHub Release '${{ inputs.release_version_number }}'
on:
  workflow_call:
    inputs:
      release_version_number:
        required: true
        type: string
      release_tag_ref:
        required: true
        type: string
      release_notes:
        description: "Release notes"
        required: false
        type: string
        default: ''
    secrets:
      release_github_token:
        required: true

env:
  GH_TOKEN: ${{ secrets.release_github_token }} # needed to run gh cli commands

jobs:

  release_publish_draft:
    name: Publish release draft and creates PR
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Creates a release draft from tag
      - name: Create GitHub Release
        run: |
          # Create a release from input tag
          gh release create --verify-tag ${{ inputs.release_tag_ref }} --title "${{ inputs.release_version_number }}" --notes "${{ inputs.release_notes }}"