name: release-publish-helm
run-name: Release Helm Charts version '${{ inputs.release_version_number }}'
on:
  workflow_call:
    inputs:
      root_helm_directory:
        required: true
        type: string
      release_version_number:
        required: true
        type: string
      release_tag_ref:
        required: true
        type: string
    secrets:
      FR_ARTIFACTORY_USER_ACCESS_TOKEN:
        required: true
      FR_HELM_REPO:
        required: true

env: 
  HELM_DIR: ${{ inputs.root_helm_directory }}

jobs:
  package_and_publish_helm:
    name: Build and publish helm chart
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
        id: checkout_release_tag
        name: checkout release tag
        with:
          ref: ${{ inputs.release_tag_ref }} # tag created by maven release plugin prepare goal
      - id: create_helm_package
        name: Create Helm Package
        run: |
          echo $PWD
          helm version
          make package_helm version=${{ inputs.release_version_number }}
      - uses: jfrog/setup-jfrog-cli@v3
        id: setup_jf_cli
        name: Setup jfrog CLI
        env:
          # JFrog platform url (for example: https://acme.jfrog.io) 
          JF_URL: ${{ secrets.FR_HELM_REPO }}
          # JFrog Platform access token
          JF_ACCESS_TOKEN: ${{ secrets.FR_ARTIFACTORY_USER_ACCESS_TOKEN }}
      - name: Publish Helm Package to repository
        id: publish_helm_package_to_repo
        run: |
          make publish_helm version=${{ inputs.release_version_number }}