name: create-release
run-name: Create release '${{ inputs.release_version_number }}'
# What it does:
# - Call release-prepare workflow
# - Call release-publish-java workflow
# - Call release-publish-release
on:
  workflow_dispatch:
    inputs:
      notes:
        description: "Release notes"
        required: false
        type: string
        default: ''
      release_version_number:
        description: "Provide release version number"
        required: true
        type: string

jobs:

  release_prepare: # prepare for a release in scm, creates the tag with the proper release versions
    name: Call release prepare
    uses: ./.github/workflows/release-prepare.yml
    with:
      release_version_number: ${{ inputs.release_version_number }}
    secrets:
      GPG_PRIVATE_KEY_BOT: ${{ secrets.GPG_PRIVATE_KEY_BOT }}
      GPG_KEY_PASSPHRASE_BOT: ${{ secrets.GPG_KEY_PASSPHRASE_BOT }}
      GIT_COMMIT_USERNAME_BOT: ${{ secrets.GIT_COMMIT_USERNAME_BOT }}
      GIT_COMMIT_AUTHOR_EMAIL_BOT: ${{ secrets.GIT_COMMIT_AUTHOR_EMAIL_BOT }}

  release_java:
    name: Call publish java
    needs: release_prepare
    uses: ./.github/workflows/release-publish-java.yml
    with:
      release_version_number: ${{ inputs.release_version_number }}
      release_tag_ref: ${{ needs.release_prepare.outputs.release_tag_ref }}
    secrets:
      FR_ARTIFACTORY_USER: ${{ secrets.FR_ARTIFACTORY_USER }}
      FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD: ${{ secrets.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}

  release_create:
    name: Call Publish Release
    needs: [release_prepare, release_java]
    uses: ./.github/workflows/release-publish.yml
    with:
      release_version_number: ${{ inputs.release_version_number }}
      release_tag_ref: ${{ needs.release_prepare.outputs.release_tag_ref }}
      release_notes: ${{ inputs.notes }}