name: release-prepare
run-name: Prepare Release '${{ inputs.release_version_number }}'
on:
  workflow_call:
    inputs:
      release_version_number:
        required: true
        type: string
      java_version:
        required: false
        type: string
        default: '17'
      require_maven:
        required: true
        type: boolean
        description: "Maven steps required to run"
    outputs:
      release_tag_ref:
        description: "Release tag"
        value: ${{ jobs.release_prepare.outputs.release_tag_ref }}
    secrets:
      GPG_PRIVATE_KEY_BOT:
        required: true
      GPG_KEY_PASSPHRASE_BOT:
        required: true
      GIT_COMMIT_USERNAME_BOT:
        required: true
      GIT_COMMIT_AUTHOR_EMAIL_BOT:
        required: true
      release_github_token:
        required: true
env:
  # Set the environment with secrets provided by the caller (secrets section)
  GIT_AUTHOR_NAME: ${{ secrets.GIT_COMMIT_USERNAME_BOT }}
  GIT_AUTHOR_EMAIL: ${{ secrets.GIT_COMMIT_AUTHOR_EMAIL_BOT }}
  GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMIT_USERNAME_BOT }}
  GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMIT_AUTHOR_EMAIL_BOT }}

jobs:
  release_prepare:
    name: Release prepare
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      release_tag_ref: ${{ steps.create_release_context.outputs.release_tag }}

    steps:
      # https://github.com/actions/checkout
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.release_github_token }}

      # set java and cache
      - name: Set Java and Maven Cache
        uses: actions/setup-java@v4
        if: ${{ inputs.require_maven }}
        with:
          distribution: 'zulu'
          java-version: ${{ inputs.java_version }}
          architecture: x64
          cache: 'maven'

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v5
        if: ${{ inputs.require_maven }}
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY_BOT }}
          passphrase: ${{ secrets.GPG_KEY_PASSPHRASE_BOT }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      # Create tag context variable
      - name: Create Release Context
        id: create_release_context
        run: |
          echo "release_tag=v${{ inputs.release_version_number }}" >> $GITHUB_OUTPUT

      # Release prepare
      # - Change the version in the POM from x-SNAPSHOT to the new version provided for the release_version_number input
      # - Transform the SCM information in the POM to include the final destination of the tag
      # - Commit the modified POM
      # - Tag the code in the SCM with a version name (v${{ inputs.release_version_number }})
      # See in the pom file the configuration '<tagNameFormat>v@{project.version}</tagNameFormat>'
      # - Bump the version in the POM to a new value, the next development iteration (y-SNAPSHOT)
      # - Commit the modified POM
      - name: Release
        if: ${{ inputs.require_maven }}
        run: |
          mvn -B release:clean release:prepare -DreleaseVersion=${{ inputs.release_version_number }}

      # create the release tag with release version number provided
      - name: Create Release Tag
        if: ${{ inputs.require_maven == 'false' }}
        run: |
          echo "Creating Release Tag: ${{ steps.create_release_context.outputs.release_tag }}"
          git tag -a ${{ steps.create_release_context.outputs.release_tag }} -m "Tag for release ${{ inputs.release_version_number }}"

      # push tag to remote repository
      - name: Push Tag
        if: ${{ inputs.require_maven == 'false' }}
        run: |
          git push origin ${{ steps.create_release_context.outputs.release_tag }}