name: release-prepare-no-maven
run-name: Prepare Release (no maven) '${{ inputs.release_version_number }}'
# Workflow to prepare the release for projects without maven
# - Creates the release branch
# - Creates the release tag
# - Push release branch and tag
on:
  workflow_call:
    inputs:
      release_version_number:
        required: true
        type: string
    outputs:
      release_branch_ref:
        description: "Release branch"
        value: ${{ jobs.release_prepare.outputs.release_branch_ref }}
      release_tag_ref:
        description: "Release tag"
        value: ${{ jobs.release_prepare.outputs.release_tag_ref }}
    secrets:
      GIT_COMMIT_USERNAME_BOT:
        required: true
      GIT_COMMIT_AUTHOR_EMAIL_BOT:
        required: true
env:
  # Set the environment with secrets provided by the caller (secrets section)
  GIT_AUTHOR_NAME: ${{ secrets.GIT_COMMIT_USERNAME_BOT }}
  GIT_AUTHOR_EMAIL: ${{ secrets.GIT_COMMIT_AUTHOR_EMAIL_BOT }}
  GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMIT_USERNAME_BOT }}
  GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMIT_AUTHOR_EMAIL_BOT }}

jobs:
  release_prepare:
    name: Release prepare no maven
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      release_branch_ref: ${{ steps.create_release_context.outputs.release_branch }}
      release_tag_ref: ${{ steps.create_release_context.outputs.release_tag }}

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
        id: checkout_master
        name: checkout master

      # Create branch context variable
      - name: Create release context
        id: create_release_context
        run: |
          echo "release_branch=release/${{ inputs.release_version_number }}" >> $GITHUB_OUTPUT
          echo "release_tag=v${{ inputs.release_version_number }}" >> $GITHUB_OUTPUT

      # create the release branch with release version number provided
      - name: create release branch
        id: create_release_branch
        run: |
          echo "Release branch: ${{ steps.create_release_context.outputs.release_branch }}"
          git checkout -b ${{ steps.create_release_context.outputs.release_branch }}

      # create the release branch with release version number provided
      - name: create release tag
        id: create_release_tag
        run: |
          echo "Release tag: ${{ steps.create_release_context.outputs.release_tag }}"
          git tag -a ${{ steps.create_release_context.outputs.release_tag }} -m "Tag for release ${{ inputs.release_version_number }}"

      # push the branch and tag to remote repository
      - name: push branch and tag
        id: push_branch_tag
        run: |
          git push -f --set-upstream origin ${{ steps.create_release_context.outputs.release_branch }}
          git push -f origin ${{ steps.create_release_context.outputs.release_tag }}
          