name: release-publish-draft-only
run-name: Release draft '${{ inputs.release_version_number }}'
# Workflow to create a release draft from release tag
on:
  workflow_call:
    inputs:
      release_version_number:
        required: true
        type: string
      release_tag_ref:
        required: true
        type: string
      release_notes:
        description: "Release notes"
        required: false
        type: string
        default: ''

env:
  GH_TOKEN: ${{ github.token }} # needed to run gh cli commands

jobs:

  release_publish_draft:
    name: Publish release draft
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
        id: checkout_release_branch
        name: checkout release branch
        with:
          fetch-depth: 0

      # Creates a release draft from tag
      - name: Create github release draft
        id: gh_release_draft
        run: |
          # Create a release from input tag
          gh release create  --draft \
          --verify-tag ${{ inputs.release_tag_ref }} \
          --title "${{ inputs.release_version_number }}" --notes "${{ inputs.release_notes }}"