name: release-publish-docker
run-name: Docker Release '${{ inputs.release_version_number }}'
on:
  workflow_call:
    inputs:
      release_version_number:
        required: true
        type: string
      release_tag_ref:
        required: true
        type: string
      with_maven:
        description: "Flag to skip the step to set java and maven configuration"
        required: false
        type: boolean
        default: true
      java_version:
        required: false
        type: string
        default: '17'
      SERVICE_NAME:
        required: true
        type: string
      GAR_RELEASE_REPO:
        type: string
        required: true
    secrets:
      GCR_CREDENTIALS_JSON:
        required: true
jobs:
  build_publish_docker_image:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        id: checkout_tag
        name: checkout tag
        with:
          ref: ${{ inputs.release_tag_ref }} # tag created by maven release plugin prepare goal

      # set java and cache
      - uses: actions/setup-java@v3
        if: ${{ inputs.with_maven }}
        id: set_java_maven
        name: set java and maven cache
        with:
          distribution: 'adopt'
          java-version: ${{ inputs.java_version }}
          architecture: x64
          cache: 'maven'

      - uses: google-github-actions/auth@v0
        id: gcloud_auth
        with:
          credentials_json: ${{ secrets.GCR_CREDENTIALS_JSON }}

      - name: Set up Cloud SDK
        id: gcloud_sdk
        uses: google-github-actions/setup-gcloud@v0

      - name: Set up docker auth
        id: gcloud_docker_auth
        run: |
          gcloud auth configure-docker

      - name: prepare context
        id: prepare_context
        run: |
          echo "GIT_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker Image
        id: build_docker
        run: |
          make docker tag=${{ env.GIT_SHA_SHORT }} repo=${{ inputs.GAR_RELEASE_REPO }}
          docker tag ${{ inputs.GAR_RELEASE_REPO }}/securebanking/${{ inputs.SERVICE_NAME }}:${{ env.GIT_SHA_SHORT }} ${{ inputs.GAR_RELEASE_REPO }}/securebanking/${{ inputs.SERVICE_NAME }}:latest
          docker tag ${{ inputs.GAR_RELEASE_REPO }}/securebanking/${{ inputs.SERVICE_NAME }}:${{ env.GIT_SHA_SHORT }} ${{ inputs.GAR_RELEASE_REPO }}/securebanking/${{ inputs.SERVICE_NAME }}:${{ inputs.release_version_number }}
          docker push ${{ inputs.GAR_RELEASE_REPO }}/securebanking/${{ inputs.SERVICE_NAME }} --all-tags
